version: "3"
services:
  app:
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/var/www/html
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"
    volumes:
      - ./Docker/mysql/data:/var/lib/mysql